# Generated by Django 4.1.4 on 2023-05-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyKURS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
