# Generated by Django 4.1.4 on 2023-05-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyKURS', '0002_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
